### ISSUE TITLE
"Hola Mundo Cruel" en Xcode 7, iOS 9, watchOS 2 con OSX El Capitan

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/ObjectiveCpdd#1]
[XCODE TUTORIAL por ISC Hola mundo.pdf](https://github.com/tectijuana/objetivecpdd/files/6420/XCODE.TUTORIAL.por.ISC.Hola.mundo.pdf)

@tectijuana/patrones15 Tenemos 3 semanas para hacer la primera aplicación en Objective/Swift checar las fechas de entrega Git.

# ACEPTAR LA ENTRADA TODO POR FAVOR (click en assignee) @tectijuana/patrones15 
> Aqui se calificará la entrada, gracias ya que lo entreguen son 12 MACS en total

**Comment by IoTeacher** [comment]
@tectijuana/patrones15 Gracias por el tiempo dedicado a sus compromisos académicos abiertamente, hay tiempos difíciles pero no dejes 2do. plano la educación, todo a su momento y aqui es sus carreras. Después, México los ocupa como profesionistas activos que paguen sus impuestos y tengan compromisos de ciudadano.

Éxito en todo lo que comprometan. Su maestro favorito René Solis

**Comment by ReyesIvan** [comment]
:feelsgood: .... yo alguna soda, pa no llevar nomas el hambre :joy:

**Comment by b081191** [comment]
a super bien y que dia seria para tambien aportar algo al convivio.

**Comment by IoTeacher** [comment]
Recuerden iMAC esa disponible para elaborar su Hola Mundo en Xcode, password es 123

**Comment by ferminreyes** [comment]
¿cuando lo acabe lo subo en github?

**Comment by IoTeacher** [comment]
@tectijuana/patrones15 ¿Calificando bloque 1 tengo muchos repetidores, será por eso se llena el laboratorio?

**Comment by Lesliecazarez** [comment]
Hola Mundo Terminado!!!!

:)
![captura de pantalla 2015-10-20 a la s 16 53 06](https://cloud.githubusercontent.com/assets/4304957/10624271/a26bbbd2-774b-11e5-979d-5371db093834.png)

**Comment by Angelkz** [comment]
Hernandez Ayala Jorge Angel - 12211450
![captura de pantalla 2015-10-20 a la s 16 41 25](https://cloud.githubusercontent.com/assets/4267059/10624287/d52a6000-774b-11e5-9524-c0d8ad8d4faf.png)

**Comment by ferminreyes** [comment]
![captura de pantalla 2015-10-15 a la s 12 42 25](https://cloud.githubusercontent.com/assets/4269543/10624297/ea95f9fe-774b-11e5-8ebb-e1e4a47bb13d.png)
Hola mundo en Xcode Objective C.

**Comment by amairanigh** [comment]
Hola Mundo Terminado Guillen Hernandez Amairani
![captura de pantalla 2015-10-20 a la s 16 52 35](https://cloud.githubusercontent.com/assets/11052768/10624317/31630bec-774c-11e5-8727-1996a9f2ef7f.png)

**Comment by Lizbethvzc** [comment]
Hola mundo terminado :+1: 
![captura de pantalla 2015-10-20 a la s 16 58 44](https://cloud.githubusercontent.com/assets/11052735/10624326/3e0c2f2c-774c-11e5-9a06-19112085b655.png)

**Comment by oscarpalma** [comment]
Hola Mundo Terminado
Palma Ahuja Oscar. 12211449


![captura de pantalla 2015-10-20 a la s 17 01 06](https://cloud.githubusercontent.com/assets/11052764/10624372/96c40568-774c-11e5-9c42-07dd0dfe7188.png)

**Comment by Miriam140214** [comment]
Actividad Terminada <3
![captura de pantalla 2015-10-21 a la s 15 26 12](https://cloud.githubusercontent.com/assets/11052511/10652205/8c0b7a30-7809-11e5-9de9-125ad68fcc6c.png)

**Comment by Alberto14** [comment]
Hola mundo Terminado!
![captura de pantalla 2015-10-21 a la s 15 21 08](https://cloud.githubusercontent.com/assets/11052682/10652236/cba00562-7809-11e5-96df-5a7caa0dc8a7.png)

**Comment by odairrobles** [comment]
Actividad Terminada, hola mundo
![captura de pantalla 2015-10-21 a la s 15 49 58](https://cloud.githubusercontent.com/assets/14007307/10652474/d2394562-780b-11e5-9797-4aae152eef34.png)

**Comment by christianbenavidez** [comment]
BENAVIDEZ RODRIGUEZ CHRISTIAN ARMANDO 12211884
HOLA MUNDO!

![captura de pantalla 2015-10-21 a la s 16 07 40](https://cloud.githubusercontent.com/assets/11052456/10652758/ffe43da8-780d-11e5-92b6-fd04d157b652.png)

**Comment by christianbenavidez** [comment]
![captura de pantalla 2015-10-21 a la s 16 10 05](https://cloud.githubusercontent.com/assets/11052456/10652801/44ce4b16-780e-11e5-9468-078dd827b8ff.png)

**Comment by HaoshengLin** [comment]
Mi Primer App!
![captura de pantalla 2015-10-21 a la s 16 08 12](https://cloud.githubusercontent.com/assets/14063655/10652817/6950c874-780e-11e5-9ff1-9056732db455.png)

**Comment by PalmiraMedina** [comment]
![captura de pantalla 2015-10-21 a la s 16 06 57](https://cloud.githubusercontent.com/assets/13953260/10652879/6b821a7a-785a-11e5-9bc6-67c1cd2f2415.png)


DONE! 
:+1:  :100: :metal: :clap: :cloud: :floppy_disk: :calling:

**Comment by ReyesIvan** [comment]
![captura de pantalla 2015-10-21 a la s 15 58 59](https://cloud.githubusercontent.com/assets/13877750/10652970/1b82b380-785b-11e5-8631-09bca876cf15.png)

Listo :goberserk: :+1:

**Comment by ISC-EliotRojas** [comment]
# Eliot Rojas Hernandez 12210353
Hola Mundo en Xcode **terminado**

![captura de pantalla 2015-10-21 a la s 16 36 41](https://cloud.githubusercontent.com/assets/6935926/10653198/1f842ae8-7812-11e5-9ce7-98d4bcbc839e.png)

**Comment by JuanSilvas** [comment]
Silvas Caro Juan de Dios #12211463
Terminado

2015-10-21 16:39 GMT-07:00 Eliot Rojas <notifications@github.com>:

**Comment by fr3edy** [comment]
Carranza Guzman Luis Alfredo
12211874
Terminado
![captura de pantalla 2015-10-21 a la s 16 55 18](https://cloud.githubusercontent.com/assets/11052704/10653446/93b600a6-7814-11e5-89aa-93f85ca821f4.png)
ado

**Comment by adlieras** [comment]
## Arias Lieras Adriana. 12211882
Hola Mundo, terminado! :dancer: 
![captura de pantalla 2015-10-21 a la s 16 55 19](https://cloud.githubusercontent.com/assets/11052591/10653502/ef3f033c-7814-11e5-8a95-7d3e1c9f932b.png)

**Comment by Ookamigmr** [comment]
Angel Arturo Castro Cortes
No. Control 12211442

![captura de pantalla 2015-10-21 a la s 17 00 55](https://cloud.githubusercontent.com/assets/7613948/10653547/56df4e16-7815-11e5-8417-e3772ef297d0.png)

**Comment by JuanSilvas** [comment]
Silvas Caro Juan de Dios
#12211463 Terminado

​

2015-10-21 17:02 GMT-07:00 Angel Castro <notifications@github.com>:

**Comment by b081191** [comment]
![captura de pantalla 2015-10-22 a la s 16 27 07](https://cloud.githubusercontent.com/assets/11052426/10681030/21209db4-78da-11e5-9863-7ce2058ff65e.png)

**Comment by iscbarragan** [comment]
Aplicacion terminada

![captura de pantalla 2015-10-22 a la s 16 41 20](https://cloud.githubusercontent.com/assets/13953281/10681230/fd605f48-78db-11e5-8719-66d46d5c3386.png)

**Comment by leonelbojorquez** [comment]
Leonel Bojorquez 
12210452
![captura de pantalla 2015-10-22 a la s 16 40 01](https://cloud.githubusercontent.com/assets/14007258/10681393/a7bddac8-78dd-11e5-87d5-114fdefa0316.png)

**Comment by ChriisL** [comment]
Hola Mundo!
Hernandez Lira Christian Leonardo
12211489
![captura de pantalla 2015-10-22 a la s 16 54 37](https://cloud.githubusercontent.com/assets/11052742/10681446/315f67c4-78de-11e5-932d-2e6217b82805.png)
![captura de pantalla 2015-10-22 a la s 16 55 00](https://cloud.githubusercontent.com/assets/11052742/10681447/31b4cd90-78de-11e5-8415-fe0d944918ba.png)

**Comment by IoTeacher** [comment]
Gracias esta actividad se cerró, solo aplica aquellos que pusieron su Hello World su nombre dentro del UIX

**Comment by becerrarodriguezraul** [comment]
Hola mundo.
Becerra Rodriguez Raul 12211902
![captura de pantalla 2015-10-22 a la s 16 13 54](https://cloud.githubusercontent.com/assets/14007326/10707014/c53c0e52-79a1-11e5-91e7-ff0985366148.png)

**Comment by Guillermsan** [comment]
Guillermo Santiago Leon
Hola mundo Terminado
![captura de pantalla 2015-10-23 a la s 16 56 50](https://cloud.githubusercontent.com/assets/11052568/10707459/8f8578ce-79a7-11e5-926a-60caf16d8508.png)

**Comment by AnaTorresPa** [comment]
Torres Paramo Ana Karen 12211420
![captura de pantalla 2015-10-23 a la s 17 32 23](https://cloud.githubusercontent.com/assets/13877770/10707738/b970f3b6-79ac-11e5-9009-53f6f2881a27.png)

**Comment by yagnacabrales** [comment]
Hola Mundo Cruel !!
Cabrales Aguayo Yagna #12210442


![captura de pantalla 2015-10-23 a la s 18 00 55](https://cloud.githubusercontent.com/assets/13877745/10708026/1f180e9a-79b0-11e5-97bb-542d0df1d048.png)

**Comment by AnaTorresPa** [comment]
Torres Paramo Ana Karen 1221420
![captura de pantalla 2015-10-23 a la s 18 02 48](https://cloud.githubusercontent.com/assets/13877770/10708046/9beb337a-79b0-11e5-806d-4d14e5040ddd.png)

**Comment by alex20078** [comment]
![captura de pantalla 2015-10-23 a la s 17 56 11](https://cloud.githubusercontent.com/assets/7757265/10708036/74ceb6e0-79b0-11e5-8ba1-9e306b2d153b.png)

TERMINADO Paz Molina Erick Alejandro

**Comment by irvingcastro** [comment]
![12210765_968743739848604_2094076050_o](https://cloud.githubusercontent.com/assets/13877823/11051008/13a73f38-8700-11e5-929c-9f37ce8a06b8.jpg)
Terminado y 11 programas quedan pendientes.
