### ISSUE TITLE
Patrón Prototype en Objective-C

### ISSUE THREAD

**Issue by abuket** [tectijuana/ObjectiveCpdd#20]
Integrantes
@DarkWolf3011 
@leonmonica

**Comment by IoTeacher** [comment]
@DarkWolf3011 
@leonmonica
 ya pasaron 2 meses y no ha puesto una foto de perfil, recuerde que GitHub es público

**Comment by IoTeacher** [comment]
Favor de armar su presentación y demas recursos en http://tectijuana.github.io/objetivecpdd/ ahi se presentará, el wiki es obligatorio tambien (puede tener copy-paste)

**Comment by IoTeacher** [comment]
@DarkWolf3011  @leonmonica @abuket favor de disolver el equipo tengo temas sin integrante, recuerde de que no debe ser patron que halla expuesto, platiquen entre ustedes.

Gracias.

**Comment by DarkWolf3011** [comment]
profesor @IoTeacher ninguno de nosotros ha expuesto este patrón, es necesario que disolvamos el equipo?
