### ISSUE TITLE
GiTarea #1

### ISSUE THREAD

**Issue by IoTeacher** [tectijuana/ObjectiveCpdd#28]
![Favo de opinar sobre estos articulos para desarrolladores](http://usuariocompulsivo.com/wp-content/uploads/2009/10/anatomia-programador.jpg "GiTarea 1")

Favor de dar su opinion atinadamente de los artículos (usar MD o MarkDown en su redacciòn):

>http://insights.dice.com/2015/10/13/apples-swift-is-killing-objective-c/?imm_mid=0da80b&cmp=em-prog-na-na-newsltr_20151017

>http://www.javaworld.com/article/2993309/careers/9-developer-trends-you-can-bank-on-in-2016.html

>http://www.infoworld.com/article/2987529/java/insider-oracle-lost-interest-in-java.html

**Comment by adlieras** [comment]
## Apple's Swift Is Killing Objective-C
No estoy familiarizada con estos lenguajes, pero es interesante como a los meses de darse a conocer Swift se convirtió muy rápido en uno de los lenguajes más comentados. Menciona que es un lenguaje de código abierto y sencillo de utilizar, y creo es importante para los desarrolladores de estas aplicaciones.

## 9 developer trends you can bank on in 2016
Pienso que es importante este artículo, ya que estas nueve tendencias sobre algunos desarrolladores nos ayuda  a tener en cuenta en que podemos trabajar o que dejamos de utilizar, de igual manera es importante como desarrolladores estar actualizados sobre los temas referentes a lo que estamos estudiando.

## Insider: Oracle has lost interest in Java
Conozco lo básico de Java, no he desarrollado mucho en dicha plataforma pero si Oracle esta perdiendo el interés en el lenguaje, sería una lastima, ya que con este artículo podría decirse que Java no está funcionando muy bien para trabajar con el. Pero de igual manera si Oracle ya no quiere trabajar con Java debido a que han tenido grandes perdidas debido a las fallas en la seguridad que tiene el lenguaje, creo que está bien que los demás se enteren y tomen mejores decisiones sobre trabajar con la plataforma Java.

**Comment by fr3edy** [comment]
## Apple’s Swift Is Killing Objective-C

este articulo en lo personal me parecio muy interesante ya que es un lenguaje para mi nuevo 
pero que ya esta en su vercion 2.0, me gusto mucho y lo que me parecio curioso esque desde 
que salio remplazo a objetive-c muy rapido ya que se convirtio muy rapido en uno de los 
mejores lenguajes, todavia no trabajo con el lenguaje pero parece que estara muy 
interesante. 

##9 developer trends you can bank on in 2016

el articulo me parecio muy buenos ya que te muestran las nuevas tecnologias y desarrollo, 
algunas tecnologias como la de noSQL me parecieron muy buenos ya que ya tenia un 
conocimiento previo a este y me gusto que explicaran algunos de los puntos fundamentales 
de las 9 que mostraron casi todos me gustaron y como el explica que las predicciones que 
haces puede que sean muy tempranas son uy buenas a mi parecer.

## Insider: Oracle has lost interest in Java

este articulo en general esta bien lo que argumenta oracle  el porque perdio el interes con jva  
y con java Enterprice una de las razones fue por la mentalidad que teine que el ganador se 
queda con todo y su comentario de que se estaban convirtiendo en una compa;ia nube  y me 
parecio bien porque estoy de acuerdo con su opinion y las razones por las cuales se quieren 
separar pero en general no e tratado con ninguno de los productos de las 2 compa;ias asi 
que no me llamo mucho la atencion el articulo.

## Carranza Guzman Luis Alfredo 12211874

**Comment by ReyesIvan** [comment]
## Articulo __"Apple's Swift Is Killing Objetive C"__

Como ya se estaba previsto a lo que se esperaba que con la llegada del nuevo lenguaje de programacion __"Swift"__ de Apple, fue creado estrategicamente de codigo abierto para poder atraer mas desarrolladores, si bien _Objective C_ segun TIOBE se encuentra en el puesto decimocuarto de los lenguajes de programacion el cual va en caida libre, podra descender mas conforme pase el tiempo, por otra parte __Swift__ va ir ascendiendo poco a poco, yo lo veo como una estrategia de Apple para atraer mas desarrolladores, no es que Swift este "_matando_" a objective-c, solo apple esta innovando, pues se debe recordar que en cualquier momento aparecen nuevas tecnologias o sistemas los cuales hacen que muchas herramientas que solian usarse pasen a ser obsoletas en este caso posiblemente esto pase con Objective-C :cry:

## Articulo __"9 Developers trends you can bank on in 2016"__
Mi opinion sobre este articulo en si trata de 9 puntos que estan pasando actualmente, desde el declive de java o el NOSQL que se espera se enfoquen muchas empresas en _confiar_ en la __nube__  para mi los q podria destacar seria que todo esta empezando a ser en tiempo real o mas bien en el 2016 estara destacando y aparte del tiempo real como ya se menciono, se empieza a manejar la _nube_ que es una tecnologia que apenas se esta empezando a querer explotar :boom: en la cual quieren agregarle el _"Self-Service"_ o autoservicio para poder dar soporte por este medio, por asi decirlo para no perder la productividad como se menciona en el articulo.

## Articulo __"Insider: Oracle has lost interest in java"__ :coffee:
En si como ya se habia visto en el articulo _"9 Developers trends you can bank on in 2016"_ java esta en declive y en este articulo se menciona el despido de altos funcionarios de java, lo que se sabe hasta ahorita es que tiene un futuro muy incierto, puesto que __Oracle__ esta enfocado mas en la _"nube"_ y de cierta manera se podria decir que es parte de la tendencias de hoy, la nube. A mi punto de vista no creo que java quede obsoleta por completo, solo es cuestion que sepan adaptarse a las nuevas tendencias ya que estamos viviendo la llamada __Revolucion del Internet de las Cosas (Internet of thing)__ y en un futuro vendra la otra revolucion que sera  _El internet de Todo_ (__Internet of Everything)__ :bulb: :bulb: :bulb: 

![ioe](https://cloud.githubusercontent.com/assets/13877750/10602017/bb7b7d5a-76ca-11e5-927d-6e1aa6d0127d.jpg)

# Reyes Coss Y Leon Ivan - 12210354

**Comment by Miriam140214** [comment]
# Mi opinión sobre Swift
Cuando Apple lanzó Swift el verano pasado, se espera que su nuevo lenguaje de programación para reemplazar finalmente Objective-C, que los desarrolladores han utilizado durante años para construir iOS y aplicaciones X Mac OS.
Creo que es bueno un cambio pero en muy difícil poder entender la sintaxis de un lenguaje tan nuevo ya que se encuentre muy poca información

# Miriam Jazmin Ildefonso Garcia -12211892

**Comment by PalmiraMedina** [comment]
## Apple’s Swift Is Killing Objective-C
--------------------------------------------------
Swift es la sensación últimamente debido a que es algo nuevo y ofrecido a código abierto, es la ley de la jungla que algo nuevo eventualmente reemplazara algo mas viejo. :cold_sweat:  Creo que la estrategia de Swift esta funcionando y esto esta beneficiando a Apple al atraer mas gente que desarrolle en el lenguaje y por ende, exista mas movimiento e innovaciones por parte del lenguaje nuevo. :computer: 
___________________________________
## 9 developer trends you can bank on in 2016
Vivimos en una época donde supuestamente *"El futuro es hoy"* y creo que tanto las empresas, como los usuarios están trabajando para que eso sea una realidad, lenguajes de programación que están cumpliendo con su ciclo y poco a poco están decayendo. Bases de datos que seran llevabas a otro nivel  y el *"Real-Time Everything"* son solo pequeñas muestras de que innovar es lo que debemos hacer para seguir avanzando. :ok_hand: 

_________________________________
## Oracle has lost interest in Java 

Con Java creo que volvemos a lo mismo de la innovación, esta es la época del *"innovarse o morir"* :floppy_disk:  :vhs: . Java necesita crear una buena estrategia para seguir vigente y revolucionarse porque la tecnología esta avanzando y Java no avanza con ella.

**Comment by DannyFranco** [comment]
## Apple's Swift Is Killing Objective-C
Siendo honesto, no estoy muy interesado en estos lenguajes, ya que la marca Apple ha venido poco a poco a la baja desde el año 2011 con la muerte de Steve Jobs. Lo peor del caso es sus excesivos precios dentro del mercado de desarrollo, Objective - C muriendo gracias a Apple's Swift no sabría a ciencia cierta que podría pasar en unos años, pero si Apple quiere ganar en desarrolladores en comparación a Android, debe optar por otras estrategias de mercadotecnia para atraer usuarios. Y más que "asesinar" a Objective - C, es como si Apple's Swift lo estuviera asimilando para ser uno mismo, ese es mi punto de vista.

## 9 developer trends you can bank on in 2016
Tal y como lo indica su nombre, hay nueve tendencias de desarrollo que van a ocurrir en el año próximo, pero hay una que resalta sobre las demás desde el punto de vista de un lector y redactor: El declive de Java como lenguaje se va a incrementar. ¿Por qué de esto? Java había sido uno de los principales lenguajes donde todos desarrollan sus aplicaciones (si no es que el principal), pero con la llegada de los móviles y sus propios lenguajes basados en Java, son los que se están apoderando del mercado de desarrollo, causante de que muchas empresas dejaran poco a poco de usar Java, y en 2016 será aún más notorio este cambio.

## Insider: Oracle has lost interest in Java
Siguiendo con mi opinión anterior, vemos que Oracle, un gigante de gestores de Bases de datos ha dicho que ha perdido interés en Java, confirma lo que mencioné anteriormente, Java viene a la baja, y es que Oracle no quiere darles armas a sus competidores ni compartir sus inovaciones. Punto en contra, ya que no todos tenemos acceso a tener un gestor como Oracle.

## Daniel Arturo Franco Cenobio - 11211222

**Comment by christianbenavidez** [comment]
### Apple’s Swift Is Killing Objective-C
Es una amenaza Swift para Objective-C debido a que el reemplazo es grande, la comunidad crece demasiado rápido y esta dejando a un lado a Objective-C, cosa que perjudica ya que esta perdiendo mucha gente y en un futuro puede desaparecer y quedar en el olvido, lo mas conveniente seria crear algo nuevo para atraer a la gente, actualizarlo en otras palabras para atraer usuarios o empezar a darle mas propaganda.

### 9 developer trends you can bank on in 2016
Un articulo muy interesante que habla sobre las 9 posibles tendencias del 2016, las cuales van cambiando y evolucionando junto con la tecnología y nos ayuda a saber sobre o darnos una idea de como va ser la tecnología o los tópicos en un futuro, te abre el panorama tecnológico y deja mucho de que pensar.


### Insider: Oracle has lost interest in Java
Se dicen muchas cosas actualmente sobre Java pero ninguna esta 100% confirmada, lo que se sabe es que Oracle tiene un compromiso muy grande con Java y actualmente existe un problema que los detiene en continuar cosa que es grave porque afecta de muchas formas a ambos y sobre Java 9 de cierta forma esta bien debido a que ayuda a los programadores de muchas formas pero a la vez puede que sea menos eficaz y no sea lo esperado en un futuro.

### Benavidez Rodriguez Christian Armando 12211884

**Comment by iscbarragan** [comment]
# Swift sobre Objective-C

Las nuevas tecnologias, en la mayoria de las ocasiones, vienen con herramientas o innovaciones mejores de las ya existentes, o por otro lado los primeros lenguajes pueden ser mejores aun que los nuevos, en gusto se rompen generos, si a un programador le gusta mas Objective-C sobre swift pues el se quedara con Objective, pero si el primero desaparece, como desarrolladores no debemos estar siempre con un lenguaje y debemos aprender, adaptarnos y movernos, no quedarnos en un mismo lugar y lenguaje. Hay que actualizarse y mas en este medio que cada dia surgen nuevas ideas.

 # 9 tendencias que podremos observan en 2016

La tecnologia evoluciona, al hombre tiene la curiosidad de saber que y como suceden las cosa. La nube en opinion muy personal es lo mejor que a surgido en el sistema, podemos de librarnos de varias cables que aun nos amarran con lo tradicional. El hecho que empresas dejaran de utilizar algunas sus herramientas habla de su filosofia de avanzar hacia el futuro y traerlo mas pronto.

# El interes que ha perdido Oracle con respecto a JAVA

Cuando tus proyectos apuntan hacia una meta, que sabras si se obtendra exito, hayque sacrificar algunas de ellas, como en la vida dejamos cosas en el pasado para seguir hacia adelante. Hasta no estar totalmente seguro de ese movimiento, no cortaran relacion. pero si es necesario terminar para obtener los mejores beneficios para ambos.

:muscle:  :baseball:

**Comment by Lesliecazarez** [comment]
##Apple’s Swift Is Killing Objective-C :+1: 
Gracias a los nuevos avances de los desarrolladores de Apple , el lenguaje de programación Swift  se ha convertido en un lenguaje que promete grandes cosas.  Me pareció muy interesante que Apple lo quiera hacer de código abierto ya que es muy útil para los programadores  que innovan en avances tecnológicos.  Aunque con el ascenso de Swift Objective-C podría quedar obsoleto.

##"9 Developers trends you can bank on in 2016" :+1: 
Mi opinión sobre este articulo y lo que me pareció mas importante es lo que se menciona sobre la decaída de Java como lenguaje ya que en la actualidad se han estado utilizando como python y Scala. Me parece muy interesante por que los nuevos lenguajes si son mas funcionales pero siempre es bueno conocer como funcionan los lenguajes clásicos.

##Insider: Oracle has lost interest in Java :+1: 

Como ya habíamos visto en el articulo anterior Java esta en descenso y en parte es por la innovación y uso y aplicación  de nuevos lenguajes que cumplen con la funcionalidad que muchos proyectos requieren, se habla de la obsolescencia de Java que ha ido en aumento en los últimos años.

##Cazarez Gil Leslie No.Control 12211434

**Comment by IoTeacher** [comment]
GRACIAS A LAS PARTICIPACIONES DE ESTA LISTA ESTA CONSIDERADO DENTRO DE LA CALIFICACION DEL BLOQUE OBJECTIVE-C.

ABAJO DE ESTE COMENTARIO YA QUEDA CERRADO Y NO ENTREGADO..
------------------------------------ABAJO DE ESTE COMENTARIO ESTA INVALIDA LA ENTREGA ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ABAJO DE ESTE COMENTARIO ESTA INVALIDA LA ENTREGA ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ABAJO DE ESTE COMENTARIO ESTA INVALIDA LA ENTREGA ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ABAJO DE ESTE COMENTARIO ESTA INVALIDA LA ENTREGA ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ABAJO DE ESTE COMENTARIO ESTA INVALIDA LA ENTREGA ------------------------------------------------------------------------------------------------------------------------------------------------------
