### ISSUE TITLE
GiTarea #1 Opinion sobre los articulos

### ISSUE THREAD

**Issue by ISC-EliotRojas** [tectijuana/ObjectiveCpdd#41]
@IoTeacher 
### Artículo: Apple's Swift is killing Objective-C
>http://insights.dice.com/2015/10/13/apples-swift-is-killing-objective-c/?imm_mid=0da80b&cmp=em-prog-na-na-newsltr_20151017

La evolución de las tecnologías a veces puede dar un cambio drástico a como las cosas funcionan en su momento y en el caso de **Objective-C** siendo reemplazado por el relativamente nuevo lenguaje de Apple *Swift*, al parecer creo caos entre la comunidad establecida alrededor de Objective-C, pero también esta creando una nueva comunidad alrededor de Swift y los planes de Apple para hacerlo de código abierto podría darle aun mas comunidad.

### Artículo: 9 developer trends you can bank on in 2016
>http://www.javaworld.com/article/2993309/careers/9-developer-trends-you-can-bank-on-in-2016.html

En el mundo **IT** el tema de **Big Data** el cual es en el sector de tecnologías de la información y la comunicación una referencia a los sistemas que manipulan grandes conjuntos de datos, esta tomando gran parte de este campo (IT) y de las tendencias que desarrolladores del 2016 para el mismo, estas tendencias siendo el almacenamiento grandes cantidades de información en la nube, todo en tiempo real y lo mas automatizado posible.

### Artículo: Insider: Oracle has lost interest in Java
>http://www.infoworld.com/article/2987529/java/insider-oracle-lost-interest-in-java.html

Existe controversia alrededor del futuro de **Java** y se dice que el compromiso que tiene **Oracle** con Java esta siendo interrumpido o esta puesto en dudas, al mismo tiempo que se planea o planeaba el lanzamiento de su actual desarrollo *Java 9*, poniendo a Java en aprietos para su futuro, al igual que las tendencias esperadas del 2016 dicen que Java será mas habitual encontrar trabajo para mantenimiento y no de desarrollo

**Comment by IoTeacher** [comment]
Gracias por esta reflexión y próxima ocasión favor de atender el Caso (issue) donde corresponda así evitar duplicarlo
