### ISSUE TITLE
GiTarea Guillen Hernandez Amairani #1

### ISSUE THREAD

**Issue by amairanigh** [tectijuana/ObjectiveCpdd#42]
Apple’s Swift Is Killing Objective-C

referente a la primera nota de Swift 
se da ha notar que Apple quería un nuevo lenguaje de programación
para poder reemplazar a Objective-C. Una vez que se creó SWift se convirtió en uno de los más hablados sobre lenguajes de programación. 

Cuando Apple decidió cambiar Objective-C para Swift, objetive-c simplmente decayó, se dice que Swift dentro de muy poco podría exceder en grado de Objective-C. Swift tiene la ventaja de que funciona perfectamente con los SDK de apple.

9 developer trends you can bank on in 2016

En esta nota se enfatizan diferentes tendencias una de ellas es Java donde menciona que muchos han mencionado que va en declive pero de igual manera estas se utilizan en diferentes empresas, la disminución de Java ha sido lento, otra tendencia que me pareció curiosa fué los desarrolladores de base de datos NoSQL donde en el futuro se añadan una gran cantidad de grandes empresas para poder adoptar públicamente NoSQL. Otra tendencia mas es "Self-service" donde depende de como los usarios interacturan con la tecnología se dice que las mejores empresas hará que los datos y los procesos de auto-servicio se construirán cultruas de rendimiento. 

Insider: Oracle has lost interest in Java

Se menciona de rumores hacera que falta de énfasis en Java dentro de la empresa. Uno de los problemas es que Oracle no esta interesado en la potenciación de sus competidores y no quiere compartir la innovación. Circularon varios correos electronicos uno sobre las sladias de personal en fin, ciertamente no se sabe exactamente el rumbo que ha tomado esta empresa solo esperan para ver que destino toma cada uno a pesar de las preocupaciones sobre las intenciones.

Guillen Hernandez Amairani

**Comment by IoTeacher** [comment]
Gracias por esta reflexión y próxima ocasión favor de atender el Caso (issue) donde corresponda así evitar duplicarlo
