### ISSUE TITLE
Opinión sobre los artículos. Oscar Palma 

### ISSUE THREAD

**Issue by oscarpalma** [tectijuana/ObjectiveCpdd#43]
## Apple’s Swift Is Killing Objective-C

El hecho de que Swift este superando a Objective-C es un indicador de que este nuevo lenguaje presenta ventajas sobre Objective-C. Apple menciona que Swift es un lenguaje fácil de aprender y de utilizar aún si nunca antes se ha programado. No estoy familiarizado con ninguno de los dos lenguajes, pero si Swift es mas fácil de utilizar y de aprender, creo que es un factor importante para los desarrolladores de aplicaciones y para aquellos que apenas se van adentrando al mundo del desarrollo de aplicaciones. 

## 9 developer trends you can bank on in 2016

Considero que es importante conocer las tendencias de desarrollo que existen en el momento, ya que es importante conocer que es lo que se esta utilizando y que es lo que ya no. Por ejemplo lo que se dice de Java de que va en declive, nos pone a pensar si es conveniente seguir aprendiendo acerca del lenguaje o mejor enfocarse a otras tendencias, como aprender sobre No Sql, el cual ofrece grandes ventajas sobre bases de datos relacionales. Uno como desarrollador debe de estar siempre actualizado, ya que de un momento a otro pueden surgir nuevas herramientas de desarrollo y hay que adaptarse a los cambios.

## Insider: Oracle has lost interest in Java

Se dice que Oracle esta perdiendo el interés en el lenguaje Java debido a las grandes perdidas que este le esta provocando debido a fallas en la seguridad del lenguaje. En lo personal me gusta desarrollar en Java ya que fue el primer lenguaje que empece a utilizar y con el cual aprendí las bases de la programación. Considero que sería una lastima si Oracle deja en el olvido a Java, ya que por muchos años este ha sido un lenguaje muy utilizado, aunque ellos tendrán sus razones para dejar de darle énfasis al lenguaje.

**Comment by IoTeacher** [comment]
Gracias por esta reflexión y próxima ocasión favor de atender el Caso (issue) donde corresponda así evitar duplicarlo
