### ISSUE TITLE
Gi Tarea, Hernández Lira Christian Leonardo

### ISSUE THREAD

**Issue by ChriisL** [tectijuana/ObjectiveCpdd#44]
## Swift

Dado el surgimiento de swift y que este fue especialmente diseñado para Apple, se a decaido mucho Objective-C ya que como bien es notorio la tecnología avanza muy rápidamente y así si tiempo después llegasen a sacar un lenguaje nuevo, quizás con correcciones que este tenga o bien solo con que saquen por así decirlo la versión 2.0 bastará para que la anterior decaiga ya que como se conoce la tecnología debe seguir evolucionando y dejando paso a nuevas tecnologías.

## Tendencias

Este artículo es un punto de vista de dicho autor, pero en lo que a mi concierne puede variar las perspectivas según la persona, aunque en una que coincido mucho es en la de tiempo real.
Ya que como bien se menciona lo mas probable es que para el 2016 esta este en pleno auge

## Oracle

En el último dado la gran competencia que existe, a un pensamiento personal, creo que es que Oracle a dejado de interesarse como antes en Java, por que es notorio resaltar que Java aún tiene un gran impacto en la actualidad, desde móvil, escritorio, etc. Mas aún así no es absoluto vencedor ya que se cuenta con miles de competidores quizás unos menores pero de igual manera competidores

**Comment by IoTeacher** [comment]
Gracias por esta reflexión y próxima ocasión favor de atender el Caso (issue) donde corresponda así evitar duplicarlo
