### ISSUE TITLE
GiTarea #1 Opinión. Vazquez Cruz Lizbeth

### ISSUE THREAD

**Issue by Lizbethvzc** [tectijuana/ObjectiveCpdd#45]
## **Swift de Apple está matando a Objective-C**

Ya que Apple lanzo swift este tuvo una gran aceptación por los programadores, ya que como bien se ve fue enfocado especialmente para realizar aplicaciones apple y de este modo dado la importancia que tomo dejo de lado a **Objective-C** el cual aunque no a pasado mucho tiempo a caído mucho de la escala en la que se encontraba
>**Fuente:** [Apple’s Swift Is Killing Objective-C](http://insights.dice.com/2015/10/13/apples-swift-is-killing-objective-c/?imm_mid=0da80b&cmp=em-prog-na-na-newsltr_20151017) 

## 9 developer trends you can bank on in 2016

En este artículo se nos mencionan 9 de las posibles tendencias del 2016, como bien se ve en dicho artículo la mayoría de ellas ya son conocidas aunque aun no marcan una tendencia tan notable como muchas lo hacen ya en la actualidad, pero aún así se ve que estas tendrán un impacto en el uso de tecnología tal y como la conocemos, es decir, puede cambiar ciertos hábitos actuales como lo es el uso de **"NoSQL"** ya que muchos en la actualidad están basados en SQL.

>**Fuente:** [9 developer trends you can bank on in 2016](http://www.javaworld.com/article/2993309/careers/9-developer-trends-you-can-bank-on-in-2016.html) 

## **Insider: Oracle has lost interest in Java**

Como bien se pudo observar en dicho artículo los intereses de las grandes compañías pueden cambiar según los pasos de los años ya que por lo regular si mencionan Java, se relaciona Oracle y viceversa, mas que nada se nota una disyunción de ideas y como ambas compañías son muy competitivas pueden llegar a tener este tipo de conflictos, pero de igual manera Java sigue siendo actualmente una empresa de mucha importancia.

>**Fuente:** [Insider: Oracle has lost interest in Java](http://www.infoworld.com/article/2987529/java/insider-oracle-lost-interest-in-java.html)

**Comment by IoTeacher** [comment]
Gracias por esta reflexión y próxima ocasión favor de atender el Caso (issue) donde corresponda así evitar duplicarlo
