### ISSUE TITLE
GIT Tarea #1 Opinion acerca de los Artculos

### ISSUE THREAD

**Issue by EstebanAngeles** [tectijuana/ObjectiveCpdd#46]
@IoTeacher 
*SWIFT<p1>*
Objective C es un lenguaje muy practico y una parte crucial en la industria de IOS develop, Ha salido un nuevo lenguaje que es mas moderno y poco mas eficiente , aunque todavía es nuevo , tiene un grna futuro. Es interesante como apple quiere hacer SWIFT open source , para que todos puedan ayudar al  desarrollo de software para IOS o aplicar a otro tipo de proyectos.

*JAVA<p1>*
Los temas que el explico y de como tiene o no futuro en la industria fue relevante ,La idea  que  NOSQL puede ser tan importante  en una industria es muy interesante  y como el  uso que se le puede dar a  NOSQL  es mucho , tanto para operaciones basicas  y operaciones criticas.

*ORACLE<p1>*
Oracle ha hecho varios cambios, pero esos cambios son para mejorar como empresa y poder inovar, Ha hecho un gran trabajo con Java development. Dichos cambios que esta empresa  intenta o planea implementar  pueden mejorar el desarrollo de java.

**Comment by IoTeacher** [comment]
Gracias por esta reflexión y próxima ocasión favor de atender el Caso (issue) donde corresponda así evitar duplicarlo
