### ISSUE TITLE
Git Tarea #1 Opiniones sobre diferentes articulos.

### ISSUE THREAD

**Issue by ferminreyes** [tectijuana/ObjectiveCpdd#47]
#Swift
Apple desarrollo un Nuevo lenguaje de programación nombrado Swift, con la finalidad de heredar y dejar atras a objective c, esto en tanto a los desarrolladores para aplicaciones moviles como de escritorio, desde entonces swift ha luchado por puestos altos de preferencia en lenguajes de programación, esto es muy importante para los desarrolladores ya que asi podremos tener una idea de que lenguajes son demandados en el área laboral, además después de algunos meses desde la salida de Swift viene la version Swift 2.0 donde se integran correcciones a errores, y mejora la SDK y la habilidad para manera errores en el desarrollo de aplicaciones utilizando este lenguaje de programación.
#Tendencias
Como sabemos, existen muchas tendencias que pueden ir evolucionando y marcando nuestro futuro, es por eso que debemos conocer los tópicos actuales en el mundo del desarrollo de software, donde se toma en cuenta las herramientas que empleamos hoy en día para el desarrollo de software, como el lenguaje de programación que debes saber manera, no solo porque sea uno muy robusto como java, sino que seas capaz de comprender que las nuevas aplicaciones ni siquiera están escritas en este lenguaje de programación, o por ejemplo las bases de datos generad en algún gestor de estas, cada vez existen mas opciones y esto debería hacernos comprender que entre mas podamos estar al dia en tanto a nuevas herramientas, mas fácil será adaptarnos y obtener trabajo fácilmente, además de que hay nuevas opciones de desarrollo, como la programación para la nube, donde lo importante es la actualización en tiempo real para todo, teniendo esto en mente es como podemos prepararnos mejor para un futuro cercano.
#Oracle
Oracle es una de las mas grandes empresas contribuyentes al desarrollo de software, y soporte para sdk’s que permitan el desarrollo del mismo, pero con el paso del tiempo las viejas herramientas van perdiendo popularidad y, por lo tanto, baja su demanda por los nuevos usuarios y desarrolladores, sin embargo Oracle, que es una empresa dueña de diferentes herramientas de software ha perdido interés en el desarrollo de nuevas tendencias, y está dejando de tener interés en algunas herramientas que ellos mismos compraron motivadamente antes, todo esto se refleja en un email donde se describen algunos aspectos cuestionables sobre el comportamiento de la empresa Oracle donde es contribuyente con otras, como sus propias herramientas internas de software.

**Comment by IoTeacher** [comment]
Gracias por esta reflexión y próxima ocasión favor de atender el Caso (issue) donde corresponda así evitar duplicarlo
