### ISSUE TITLE
GITarea #1 Reyes Coss Y Leon Ivan

### ISSUE THREAD

**Issue by ReyesIvan** [tectijuana/ObjectiveCpdd#48]
## Articulo __"Apple's Swift Is Killing Objetive C"__

Como ya se estaba previsto a lo que se esperaba que con la llegada del nuevo lenguaje de programacion __"Swift"__ de Apple, fue creado estrategicamente de codigo abierto para poder atraer mas desarrolladores, si bien _Objective C_ segun TIOBE se encuentra en el puesto decimocuarto de los lenguajes de programacion el cual va en caida libre, podra descender mas conforme pase el tiempo, por otra parte __Swift__ va ir ascendiendo poco a poco, yo lo veo como una estrategia de Apple para atraer mas desarrolladores, no es que Swift este "_matando_" a objective-c, solo apple esta innovando, pues se debe recordar que en cualquier momento aparecen nuevas tecnologias o sistemas los cuales hacen que muchas herramientas que solian usarse pasen a ser obsoletas en este caso posiblemente esto pase con Objective-C :cry:

## Articulo __"9 Developers trends you can bank on in 2016"__
Mi opinion sobre este articulo en si trata de 9 puntos que estan pasando actualmente, desde el declive de java o el NOSQL que se espera se enfoquen muchas empresas en _confiar_ en la __nube__  para mi los q podria destacar seria que todo esta empezando a ser en tiempo real o mas bien en el 2016 estara destacando y aparte del tiempo real como ya se menciono, se empieza a manejar la _nube_ que es una tecnologia que apenas se esta empezando a querer explotar :boom: en la cual quieren agregarle el _"Self-Service"_ o autoservicio para poder dar soporte por este medio, por asi decirlo para no perder la productividad como se menciona en el articulo.

## Articulo __"Insider: Oracle has lost interest in java"__ :coffee:
En si como ya se habia visto en el articulo _"9 Developers trends you can bank on in 2016"_ java esta en declive y en este articulo se menciona el despido de altos funcionarios de java, lo que se sabe hasta ahorita es que tiene un futuro muy incierto, puesto que __Oracle__ esta enfocado mas en la _"nube"_ y de cierta manera se podria decir que es parte de la tendencias de hoy, la nube. A mi punto de vista no creo que java quede obsoleta por completo, solo es cuestion que sepan adaptarse a las nuevas tendencias ya que estamos viviendo la llamada __Revolucion del Internet de las Cosas (Internet of thing)__ y en un futuro vendra la otra revolucion que sera  _El internet de Todo_ (__Internet of Everything)__ :bulb: :bulb: :bulb: 

![ioe](https://cloud.githubusercontent.com/assets/13877750/10602017/bb7b7d5a-76ca-11e5-927d-6e1aa6d0127d.jpg)

**Comment by IoTeacher** [comment]
Gracias por esta reflexión y próxima ocasión favor de atender el Caso (issue) donde corresponda así evitar duplicarlo
