### ISSUE TITLE
GIT Tarea #1 Opinion acerca de los Artculos

### ISSUE THREAD

**Issue by DarkWolf3011** [tectijuana/ObjectiveCpdd#49]
# Apple's Swift is killing Objective-C
Con el paso del tiempo la tecnologia avanza y para adaptarse a las nuevas tendencias y necesidades, a veces se tiene que hacer un gran cambio, en este caso es la evolucion del lenguaje de **Objective C**, para darle lugar a un nuevo lenguaje _Swif._ Con esto empieza una nueva era, creando nuevas comunidades, nuevas oportunidades y nuevas ideas, orientando a todos a avanzar y aprender nuevas cosas, para adecuarnos al paso de la tecnologia.

# 9 developer trends you can bank on in 2016
Hoy en dia existen muchas tendencias las cuales van cambiando y evolucionando junto con la tecnologia en este articulo se nos comparten las tendencias que supuestamente estaran en el 2016 esto para que las personas como nosotros tengamos una certeza de cuales seran los topicos de la tecnologia en un futuro proximo y asi podramos enfocarnos en ellos para poder ser competentes en el mundo y no quedarnos obsoletos.

# Oracle has lost interest in Java
Oracle es una gran empresa y tiene un gran prestigio en el desarrollo de software y tiene una gran referencia al escuchar la palabra **"java"** puesto que han trabajado juntos un largo tiempo, sin embargo a veces una tecnologia deja de funcionar igual que siempre, tal vez por el hecho de que no  es muy nueva, o bien que es facilmente superada por las demas, lo cual la convierte  en un negocio no viable y bien como cualquier empresa **oracle** sabe tomar deciciones sean faciles o dificiles, un negocio es un negocio y si **java** no mejora bien podria pasar a la historia.

**Comment by IoTeacher** [comment]
Gracias por esta reflexión y próxima ocasión favor de atender el Caso (issue) donde corresponda así evitar duplicarlo
