### ISSUE TITLE
GiTarea #1 Opinión. Madrigal Raul 

### ISSUE THREAD

**Issue by abuket** [tectijuana/ObjectiveCpdd#50]
**Apple’s Swift Is Killing Objective-C**

con el lanzamiento de el lenguaje swift, Apple ha decidido enfocar toda su atencion en el, dejando a Objective-C en segundo plano ya que swift ha tenido una gran aceptacion por los programadores y ha escalado en posiciones el ranking de lenguajes de programacion muy rapido en base a su lanzamiento.Y hay planes de hacer swift open-source!!!!!!!.

**9 developer trends you can bank on in 2016**

Este artículo es un punto de vista donde se mencionan las 9 posibles tendencias del 2016 la mayoria de estas tendencias ya estan en las mentes de muchas personas aunque puede que no sean muy notables; pero cabe mencionar que estas tendecias pudieran ocasionar un gran cambio en la tecnologia.

**Oracle has lost interest in Java**

Personalmente creo que este articulo fue el mas interesante de todos , ya que uno relaciona a oracle con java y viceversa el hecho de que oracle al parecer se convierta en una compania de nube, no creo que java desaparesca de un dia para otro, solo es cuestion que se adapten a los cambios.

Links:
http://insights.dice.com/2015/10/13/apples-swift-is-killing-objective-c/?imm_mid=0da80b&cmp=em-prog-na-na-newsltr_20151017
http://www.javaworld.com/article/2993309/careers/9-developer-trends-you-can-bank-on-in-2016.html
http://www.infoworld.com/article/2987529/java/insider-oracle-lost-interest-in-java.html

**Comment by IoTeacher** [comment]
Gracias por esta reflexión y próxima ocasión favor de atender el Caso (issue) donde corresponda así evitar duplicarlo
