### ISSUE TITLE
GiTarea #1 Opinión Julio Monica

### ISSUE THREAD

**Issue by leonmonica** [tectijuana/ObjectiveCpdd#51]
Apple’s Swift Is Killing Objective-C

Desde que Apple lanzó Swift, se esperaba que ese nuevo lenguaje de programación reemplazara a Objective-C, que los desarrolladores han utilizado durante años para construir iOS y aplicaciones X Mac OS. "Poco después de que Apple anunció que cambiar de Objective-C para Swift, Objective-C entró en caída libre", decía el texto de TIOBE, Y creo que no tardara mucho en que eso suceda debido a que la tecnologia va avanzando y se empiezan a inovar muchar cosas.

9 Developers trends you can bank on in 2016

Mi opinion acerca de este articulo que incluye 9 puntos es que como se ha estado viendo hoy en dia los servicios de la nube se estan utilzando cada vez mas y se han vuelto mas confiables y poco a poco eso empieza a ser preferible por muchas compañias.

Insider: Oracle has lost interest in Java

En mi opicion talvez java esta teniendo malas deciciones o y Oracle que empieza a tener mas enfoque en servivios de nube le hacen estan afectando a Java. Lo que puede pasar es que Java empieze a deacer.

**Comment by IoTeacher** [comment]
Gracias por esta reflexión y próxima ocasión favor de atender el Caso (issue) donde corresponda así evitar duplicarlo
