### ISSUE TITLE
GiTarea#1 Arias Lieras Adriana

### ISSUE THREAD

**Issue by adlieras** [tectijuana/ObjectiveCpdd#52]
## Apple's Swift Is Killing Objective-C
No estoy familiarizada con estos lenguajes, pero es interesante como a los meses de darse a conocer Swift se convirtió muy rápido en uno de los lenguajes más comentados. Menciona que es un lenguaje de código abierto y sencillo de utilizar, y creo es importante para los desarrolladores de estas aplicaciones.

## 9 developer trends you can bank on in 2016
Pienso que es importante este artículo, ya que estas nueve tendencias sobre algunos desarrolladores nos ayuda  a tener en cuenta en que podemos trabajar o que dejamos de utilizar, de igual manera es importante como desarrolladores estar actualizados sobre los temas referentes a lo que estamos estudiando.

## Insider: Oracle has lost interest in Java
Conozco lo básico de Java, no he desarrollado mucho en dicha plataforma pero si Oracle esta perdiendo el interés en el lenguaje, sería una lastima, ya que con este artículo podría decirse que Java no está funcionando muy bien para trabajar con el. Pero de igual manera si Oracle ya no quiere trabajar con Java debido a que han tenido grandes perdidas debido a las fallas en la seguridad que tiene el lenguaje, creo que está bien que los demás se enteren y tomen mejores decisiones sobre trabajar con la plataforma Java.

**Comment by IoTeacher** [comment]
Gracias por esta reflexión y próxima ocasión favor de atender el Caso (issue) donde corresponda así evitar duplicarlo
