### ISSUE TITLE
GitTarea#1 opinion de articulo becerra rodriguez raul

### ISSUE THREAD

**Issue by becerrarodriguezraul** [tectijuana/ObjectiveCpdd#54]
Swift de Apple está matando a Objective-C

se habla sobre el nuevo lenguaje que sustituira a objective c ya que esta siendo muy popular entre los desarrolladores auque objective c tenia muy bien con ios .

9 tendencias desarrollador usted puede contar en 2016

se habla de como va en decadencia el lenguaje java  pero de esto solo se especula y se menciona el lenguaje nosql y su utilización para los autoservicios, 

Insider: Oracle ha perdido el interés en Java

se habla sobre la falta de enfasis en java y de los problemas que tiene oracle que no desea compartir  la innovacion, Oracle está deshaciendo. Aprenda algo nuevo - o ser el antiguo desarrollador Cobol unidad central del futuro y la esperanza de montar a cabo hasta la jubilación.

**Comment by IoTeacher** [comment]
Gracias y próxima ocasión favor de atender el Caso (issue) donde corresponda así evitar duplicarlo.
