### ISSUE TITLE
GitTarea #2 Ranking de App Store

### ISSUE THREAD

**Issue by yagnacabrales** [tectijuana/ObjectiveCpdd#57]

**Comment by IoTeacher** [comment]
### https://www.appannie.com/ nos da un ranking de Apps Stores por Pais, categoria, pago o gratis, etc. revisarlo y dar la opinion/comparación. 

## Enfocarse a Apps Store Apple

## Puede compararlo con Google Play vs App Store, e intercesora de categorias de interes.

Favor de subscribiese con este proveedor.

René

**Comment by Miriam140214** [comment]
Mi opinion sobre!!
![app](https://cloud.githubusercontent.com/assets/11052511/10860124/a1b1b984-7f21-11e5-9866-f9132b5fe64d.jpeg)

**Comment by Alberto14** [comment]
App Annie

Las herramientas de análisis de las principales tiendas de apps, App Store y Android Market, están bien pero proporcionan una información que se queda corta en muchos casos. Por ello han surgido varias herramientas que permiten un seguimiento mucho más detallado e intenso del rendimiento, distribución y resultados de nuestras apps.

App Annie centrada en el Apple App Store. De momento es gratuita, y aunque ya ofrece un servicio de Intelligence de pago, es posible que acaben por hacerlo de pago. También permite ver los rankings, ventas, reviews, etc. Además permite ver el histórico con la mejor posición conseguida por la app en su historia. Permite consultar además algunos de los datos de rendimiento de otras aplicaciones, las de la competencia, como la posición que han ido ocupando desde su lanzamiento en varios países.

http://www.aplicacionesmovil.com/wp-content/uploads/170495v2.png

**Comment by christianbenavidez** [comment]
![app](http://livedoor.blogimg.jp/sgreport/imgs/a/1/a1a8a53c.png)

**Comment by ilianacm** [comment]
App Annie es una compañia dedicada a los informes de aplicaciones con mayor ranking, nos permite ver las aplicaciones con mayor popularidad en el mundo de internet.


![a6efce1b9d16fdfa7de44f3cb58f8c5495ee7b5c jpg](https://cloud.githubusercontent.com/assets/14007302/10860941/7e256812-7f71-11e5-85d6-88b80de857e9.png)

**Comment by fr3edy** [comment]
mi opinion sobre:
![image](https://cloud.githubusercontent.com/assets/11052704/10861933/f4e2a6b4-7f48-11e5-9355-fda7ff55a0e9.png)

**Comment by adlieras** [comment]
## App Annie :calling: 
Es una compañía dedicada a producir herramientas de inteligencia de negocios y los informes de mercado para la industria de aplicaciones y productos digitales. De igual manera, me parece que es una muy buena app, ya que te muestra cuales son las aplicaciones más utilizadas ya sea desde diferentes categorías, las gratuitas, las de pago y hasta por país, y no muchos sabíamos de estos tops.

En lo personal ya he utilizado tanto AppsStore como Google Play,  y los dos me gustan, aunque cabe mencionar que en Google Play es un poco más gratuito que AppsStore, y respecto a funcionalidad las dos se me hace que están muy completas, aunque una tenga aplicaciones que atraen más al público en general que la otra. Pude observar que tanto en AppsStore como en Google Play, unas de las más utilizadas son las redes sociales, y esto es debido a que gracias a la tecnología podría decirse que existe más comunicación entre las personas.

![captura de pantalla de 2015-10-30 22 19 57](https://cloud.githubusercontent.com/assets/11052591/10862069/a718e1d8-7f56-11e5-823d-c777c20fecdd.png)

**Comment by Lesliecazarez** [comment]
### App Annie :+1: 

App Annie es una aplicación en la cual podemos ver estadísticas de mercado y nos muestra cuales son las aplicaciones mas populares, muestra estadísticas de aplicaciones, descargas y competidores.  Me perece interesante ya que con esta aplicación podemos monitorear, gracias a su Analytics Dashboard, las descargas de nuestra aplicación, los ingresos, las palabras clave, comentarios, uso de datos y de publicidad en una plataforma consolidada. Descubren oportunidades para hacer crecer su audiencia global, mejorar el tiempo invertido en su aplicación, y maximizar los ingresos.

Mi opinión sobre AppsStore y PlayStore es que ambas son buenas pero PlayStore te da opciones de aplicaciones gratuitas, aunque appstore te brinda mas seguridad en ese aspecto.

![appanie](https://cloud.githubusercontent.com/assets/4304957/10865468/228852e6-7fc9-11e5-9083-b9bb33095a40.jpg)

**Comment by abuket** [comment]
App annie
provee un servicio de análisis del mercado inteligente para que los desarrolladores de aplicaciones tengan en mente la tendencia actual del mercado y así puedan crear aplicaciones orientadas hacia lo que esta de moda.

Actualmente ya es un negocio global que esta presente actualmente en 7 países y muchas culturas diferentes.

Para finalizar pienso que es una gran idea poder compararte con la competencia así se crea un mercado competitivo que pueda ofrecer calidad a un buen precio.

![Alt Text](http://www.weathercast.co.uk/uploads/pics/App-Annie.png)

**Comment by oscarpalma** [comment]
Por medio de App Annie podemos ver el top de las aplicaciones de las diferentes tiendas de aplicaciones. Es muy útil cundo se desea desarrollar aplicaciones, por que así se puede conocer cual es la tendencia en cada una de las diferentes plataformas, como iOS o Android en los diferentes países y así enfocar el desarrollo hacia las tendencias actuales. También podemos conocer que ofrecen las aplicaciones y compararlas con otras, para poder seleccionar la que se ajusta a lo que queremos.

Ademas de podemos observar el top por compañía.

![top companias](https://cloud.githubusercontent.com/assets/11052764/10866467/43dca184-7fe4-11e5-8956-d6d20c77cf2f.PNG)


Podemos observar que tanto en la App Store y en Google Play, Whats app, Messenger, y Facebook se mantienen a la cabeza, debido a que la mayoría utiliza las redes sociales.
En cambio otras aplicaciones tienen un lugar en el top ligeramente separados en iOS y en Google Play, como por ejemplo: YouTube en el top de iOS se encuentre en el lugar numero 5 y en la Google Play se encuentre en el número 26.

![youtube ios](https://cloud.githubusercontent.com/assets/11052764/10866482/e9ccb408-7fe4-11e5-8151-b8895a17a409.PNG)

![youtube google](https://cloud.githubusercontent.com/assets/11052764/10866484/ed83b2cc-7fe4-11e5-93b4-3d582d9a340e.PNG)


Otra aplicación que observe, fue dropbox, que en iOS aparece en el lugar 83 y en Google Play aparece en el lugar 317, una diferencia muy grande. 

![drop box ios](https://cloud.githubusercontent.com/assets/11052764/10866500/57452ff6-7fe5-11e5-8dca-d5369bdd849a.PNG)

![drop box google](https://cloud.githubusercontent.com/assets/11052764/10866507/b7008396-7fe5-11e5-86a2-481769d2e925.PNG)

**Comment by amairanigh** [comment]
App Annie  nos proporciona una estadística enorme sobre diferentes aplicaciones, dependiendo de las plataformas las aplicaciones incluidas ahí son de diferentes categorías, dependiendo de la plataforma como iOS, WindowsPhone, Android, etc. y del número de descargas y la utilización productiva se deriva el TOP de las aplicaciones. Sin olvidarse que también del país son las aplicaciones que se presentan en mejores posiciones. Podemos observar la diferencia en las primeras 5 posiciones entre iOS y Android
Ejemplo en iOS de EUA los top son los siguientes
![a1](https://cloud.githubusercontent.com/assets/11052768/10867409/36c1e834-8015-11e5-9af6-c6b0d831382a.png)

Y en iOS en México las primeras 5 posiciones son estas aplicaciones:
![a2](https://cloud.githubusercontent.com/assets/11052768/10867414/57faace8-8015-11e5-9cfc-426cd19e3947.png)


Aquí nos permiten visualizar diferentes aplicaciones productivas dependiendo de la necesidad del usuario y del país donde es ubica.

 http://technode.com/wp-content/uploads/2013/10/a6efce1b9d16fdfa7de44f3cb58f8c5495ee7b5c.jpg.png

**Comment by iscbarragan** [comment]
h1 App Annie

Como desarrolladores debemos estar pendientes de las tendencias tecnologicoas, en este caso las aplicaciones. Debemos estar pendientes sobre lo que la gente esta utilizando y asi estan al tanto sobre que debemos desarrolllar, conociendo el gusto de la gente.

![123](https://cloud.githubusercontent.com/assets/13953281/10870341/25d3c796-807d-11e5-9b76-066bc138bd91.png)

**Comment by Lizbethvzc** [comment]
# **App Annie**

>App Annie es una compañía de inteligencia de negocios y analista con sede en San Francisco, California. Produce herramientas de inteligencia de negocios y realiza  informes de mercado para la industria de aplicaciones y productos digitales dependiendo de la región.

App Anni es una gran herramienta para los interesados en desarrollar una aplicación movil.
App Annie genera un informe de ventas de diferentes plataformas de venta, entre los más destacados, y de los que se hablara en esta tarea, son IOs y Google Play.
El estudio revela que mientras Apple es líder indiscutible en los ingresos, obtenidos gracias a las buenas ventas de aplicaciones en su tienda iOS, la tienda de Google con apps para Android es la que tiene con diferencia mayor número de descargas.
En lo referente a la facturación conseguida por Apple en su tienda App Store, esta ya es un 80 por ciento más elevada que la conseguida por su rival Google Play.

Enfocandonos en una zona, en este caso México, se puede apreciar que las redes sociales es lo más descargado en ambas plataformas, en lo que respecta a las aplicaciones de descarga en modo gratuito. 
IOs: ![Alt Text](https://scontent-lax3-1.xx.fbcdn.net/hphotos-xap1/v/t35.0-12/12197381_10208362393000379_741374147_o.jpg?oh=a830398b5bb88971c7728137539b6b46&oe=5638C0AA)
Google Play: ![Alt Text](https://scontent-lax3-1.xx.fbcdn.net/hphotos-xfa1/v/t34.0-12/12207982_10208362406040705_1998406711_n.jpg?oh=4a4f1aa939514d0ebaca398c1648aef7&oe=563911DD)

Ambas plataformas manejan diferentes aplicaciones, y algunas luego se encuentran en forma de paga y en la otra plataforma de forma gratuita. 
Esta clase de informes son necesarios para poder saber en que plataforma es más conveniente lanzar nuestra aplicación y saber en que punto tendrá más venta.

**Comment by DarkWolf3011** [comment]
# App Annie
App Annie es una  herramienta para los que desean en desarrollar una aplicación movil, esta genera un informe de ventas de las diferentes plataformas de venta, como lo son son **AppStore (Apple), Microsoft, Amazon y Google Play**.
Aqui se nos presenta de manera clara las aplicaciones dominantes en cada tienda, tanto de paga como gratuitas ademas de proveernos de una reporte sobres las ganancias y descargas que se generan en cada plataforma. Para aquellos programadores de aplicaciones moviles, esto es muy util pues te permite saber como esta el mercado en el que pondras a la venta tu aplicacion, y de que manera te conviene hacerlo, ya sea gratis o de paga, de manera que te da toda la informacion necesaria para poder tomar una decision con buenas buenas decisiones a fin de tomar el menor riesgo posible.
 ![Alt Text](http://livedoor.blogimg.jp/sgreport/imgs/a/1/a1a8a53c.png)

**Comment by leonmonica** [comment]
App Annie es una compañía de inteligencia de negocios y analista, Produce herramientas de inteligencia de negocios una de ellas es un servicio gratuito en línea para el análisis de clasificación de aplicaciones. 
Proporciona una serie de gráficos que visualizan en el ranking histórico , las clasificaciones diarias, calificaciones con colocaciones desglosados por países y categorías de las 1.000 aplicaciones en todo el iOS , Mac, Google Play , Amazon Appstore, Windows Store Phone y Windows 8 Store .


![app annie](https://cloud.githubusercontent.com/assets/11052781/10877166/86598bf2-80f8-11e5-93c0-b488a3be9c51.png)

**Comment by Guillermsan** [comment]
App Annie es una herramienta en la que  podemos ver el top de las aplicaciones de las diferentes tiendas de aplicaciones. Es de mucha utilidad  cundo se desea desarrollar aplicaciones, por que así se puede conocer cual es la tendencia en cada una de las diferentes plataformas, También podemos conocer que ofrecen las aplicaciones y compararlas con otras, para poder seleccionar la que se ajusta a lo que queremos, nosotros como estudiantes debemos de aprovechar este tipo de herramientas para desarrollar nuevas apps que nos puedan abrir nuevas puertas laborales en un futuro



![image](https://cloud.githubusercontent.com/assets/11052568/10891240/9c83761e-8151-11e5-9f60-20de8ca06346.png)

**Comment by Angelkz** [comment]
App Annie me ha permitido lograr un curioso interés basado en mis gustos, gracias a un pequeño filtro que termine haciendo al comparar el top de aplicaciones de Videojuegos en México tanto en IOS como en Google Play, donde termine encontrando que las estadisticas de estos dos lugares son realmente muy distintos a la manera que yo pensaba, por lo que puedo concluir que la utilidad de esta aplicación para la toma de decisiones si es relevante.

![image](https://cloud.githubusercontent.com/assets/4267059/10891614/d2288474-8153-11e5-94ea-9ce2862c7928.png)

![image](https://cloud.githubusercontent.com/assets/4267059/10891409/b54889e0-8152-11e5-8118-7202dc03f38e.png)

**Comment by ISC-EliotRojas** [comment]
#  App Annie

**App Annie** es una herramienta poderosa que permite a los desarrolladores mantener una visualización de las aplicaciones en el mercado y la tendencia que llevan las aplicaciones, no solo de cierto dispositivo o de cierto país sino de diferentes lugares y dispositivos, teniendo así un gran vision de conjunto sobre las aplicaciones desarrolladas y así ayudar a los desarrolladores a ver las estadísticas del mercado y que es lo que los usuarios prefieren y que no..

Podemos ver que las aplicaciones mas famosas son las de redes sociales ya que en estos días casi todos tenemos al menos un perfil en una red social en segundo lugar podía decir que las aplicaciones de entretenimiento (juegos) son las mas solicitadas por los usuarios.

Comparación de México con Estados Unidos:

![appstoretop](https://cloud.githubusercontent.com/assets/6935926/10901385/1bf1e1ec-81a2-11e5-9b1c-0578ae516782.png)

![appstoretop2](https://cloud.githubusercontent.com/assets/6935926/10901386/2277088a-81a2-11e5-8ba6-645df64fc8e2.png)

**Comment by Alberto80** [comment]
App Annie nos ofrece información sobre la facturación y los porcentajes de las grandes empresas como App Store y Google Play quienes por poner un ejemplo han obtenido los mayores porcentajes en ranking, teniendo en cuenta que la mayoria de las descargas son de redes sociales, edición de imagen, video, aplicaciones para moviles, musica y diseño como son los temas del telefono.

![images](https://cloud.githubusercontent.com/assets/14007333/10902215/72168d7c-81af-11e5-9aa4-82507acf1df5.jpeg)

**Comment by EstebanAngeles** [comment]
App Annie es una compañía de inteligencia de negocios y analista con sede en San Francisco, California. Produce herramientas de inteligencia de negocios y los informes de mercado para la industria de aplicaciones y productos digitales.
Lo que esta empresa  hace es ayudar a uno estar al día , con el mercado de aplicaciones, y saber que es lo que  esta de moda, al igual que las áreas donde son mas populares.
La pagina maneja por apps gratuitas , mas populares y las apps que cuestan.

![1](https://cloud.githubusercontent.com/assets/13890936/10902304/99ef4176-81b0-11e5-8606-344eb912eb79.png)

**Comment by PalmiraMedina** [comment]
## App Annie 

Siempre que decidimos crear alguna aplicación las preguntas que nos hacemos son:
¿Para que s.o?
¿De qué tema hacerla?
¿Qué es lo que esta de moda?

y si no encontramos las respuestas que deseamos pues nos aventamos a nuestra suerte y criterio a responder esas preguntas. Con App Annie todas esas preguntas pueden ser respondidas con el simple hecho de registrarnos y navegar en ella, y lo digo personalmente como es bastante sorprendente las diferencias de rankings entre países e inclusive entre usuarios de plataformas.
Desde IOS hasta Amazon, gratuitas o de paga, sin duda para todos los gustos hay y los gustos son los que sorprenden. Lo que nosotros podríamos creer que no puede *"pegar"* en la app store, resulta que es uno de los mas descargados, o viceversa.
Lo que siempre debemos tener en cuenta es, que, a la hora de desarrollar debemos investigar y ponernos en *"los zapatos de los usuarios"* para que nuestros proyectos sean exitosos.

![evidenciaappannie](https://cloud.githubusercontent.com/assets/13953260/10902366/a01d9f24-81b1-11e5-9165-2bc5314b4063.JPG)

__________
Palmira Medina 11211228

**Comment by ReyesIvan** [comment]
# App annie
#### Reyes Coss Y Leon Ivan 12210354
--------------------------
Es un portal en el cual podemos tener conocimiento de las tendencias actuales en las aplicaciones, para ios, windows phone, google,etc.
Para poder acceder a esta informacion ocupas registrarte como usuario, al finalizar esto podras ver por secciones cuales son las aplicaciones de paga o gratuitas mas descargadas en la fecha que uno desea y seleccionar tambien el pais, esto nos permite saber que es lo que tiene mas exito en nuestro pais, por ejemplo si seleccionas mexico y la fecha "3 de noviembre" podemos ver las apps que estan en auge al dia, en este caso las gratuitas son puras redes sociales y las de paga son puros juegos, en el sistema __IOS__, con esto uno puede determinar que al mexicano le interesa mas las apps de entretenimiento y asi podemos recaudar informacion y obtener ideas de que desarrollar para tener exito, en este caso si vas a desarrollar una app para ios en mexico y esperas obtener interes del publico, tendria que ser un juego.

![app annie](https://cloud.githubusercontent.com/assets/13877750/10908205/e9f89c24-81e4-11e5-81bb-8ea063b6a9ad.png)

**Comment by karenmg92** [comment]
App Annie nos abre paso por los rankings de todas las aplicaciones de las tiendas virtuales, es una herramienta de gran utilidad. Con tan solo crearte una cuenta gratuita puedes consultar las tendencias en los rankings a lo largo del tiempo y con distintos filtros, lo que resulta una herramienta útil para, por ejemplo, comprobar la eficacia de tu plan de marketing.
Es una herramienta facil de utilizar debido a que cuenta con una visualizacion facil de entender, ademas nos ofrece la facilidad de crear grupos para que la gente que pertenezca a nuestra organicacion pueda acceder a la informacion que nosotros queramos y de esta manera lograr un desarrollo mas eficaz de manera grupal. Sin duda es una herramienta de gran utilidad. 

![capture](https://cloud.githubusercontent.com/assets/14100949/10916336/d80a6206-820f-11e5-917b-2bcda1658bb0.PNG)

**Comment by b081191** [comment]
App Annie por el momento es una aplicación gratuita que sirve como herramienta de análisis de aplicaciones. Esto con el fin de ver los ranking de app, ventas , reviews, etc. ademas permite ver el historico con la mejor posicion conseguida por la app. Ademas permite consultar algunos datos de rendimiento de las aplicaciones.las de competencias, como la de la posicion que ocupa al momento de la  revisión.





![appnie](https://cloud.githubusercontent.com/assets/11052426/10924881/d802ac12-823e-11e5-9ce0-c2d33a69c062.jpg)

<h2> Brenda Zaragoza Nava 11210342 </h2>

**Comment by abigailmares** [comment]
Mares Mireles Mariana Abigail 12210458

App Annie: Con el gran numero de aplicaciones móviles disponibles en el mercado surgen nuevas herramientas que son de mucha utilidad para los desarrolladores, una de las principales necesidades es analizar el real funcionamiento y rendimiento de las aplicaciones en una amplia variedad de mercados y plataformas.

Para esto se ha desarrollado una nueva herramienta para tener más seguimiento mucho más detallado el rendimiento y distribución de las apps.

Una herramienta muy eficaz es App Annie  también centrada en el Apple App Store. También permite ver los rankings, ventas. De igual manera, se puede consultar además algunos de los datos de rendimiento de otras aplicaciones.

![sin titulo](https://cloud.githubusercontent.com/assets/14007242/10925315/c381e93a-8241-11e5-8acb-6d58304de2c5.png)

**Comment by odairrobles** [comment]
Odair Robles Paz 12210436

APP ANNIE
Esta herramienta nos proporciona darle seguimiento mas preciso y especifico al rendimiento de las apps.
nos permite ver los rankins de ventas-descargas de las apps, y nos da muchas mas opciones sobre otras aplicaciones,
con el gran incremento dia tras dia de nuevas aplicaciones moviles y que muchas son de gran utilidad y efectividad se requiere y se busca la necesidad de checar el rendimiento, la capacidad y funcionamiento de estas. asi que por lo tanto esta app anni es ideal para ello,.

![app anni](https://cloud.githubusercontent.com/assets/14007307/10925946/84ca8214-8247-11e5-92ac-2eeb3e5b0cbc.png)

**Comment by HaoshengLin** [comment]
## Lin Haosheng 11211624
La misión es crear la próxima generación de soluciones de inteligencia de negocios para la economía de aplicaciones global. En una industria que está creciendo de manera exponencial , App Annie está proporcionando a las empresas más exitosas con productos de datos que están informando a la totalidad de sus estrategias de tienda de aplicaciones , ya sean editores de aplicaciones, las compañías de medios , inversores , marcas o plataformas de contenidos .


![sin titulo](https://cloud.githubusercontent.com/assets/14063655/10925932/5730fa86-8247-11e5-8f51-10c52f1efb7a.png)

**Comment by DannyFranco** [comment]
![app](https://cloud.githubusercontent.com/assets/11052511/10860124/a1b1b984-7f21-11e5-9866-f9132b5fe64d.jpeg)

##Franco Cenobio Daniel Arturo 11211222
Debido a la gran demanda de aplicaciones móviles y el "Boom" de los teléfonos inteligente, AppAnnie se encarga de mostrarnos que aplicaciones son las más requeridas/descargadas/demandadas de todas las compañías, llámese Google, Windows o IOS, vemos un pequeño ejemplo con una aplicación que viene ganando fama muy rápido, el famoso "Snapchat".

![ScreenShot](https://d1h69ey09xg1xv.cloudfront.net/wp-content/uploads/2014/01/app-annie-720x519.png)

**Comment by ZunigaGabriel** [comment]
# Opinion : App Annie
## Zuniga Castillo Gabriel Eduardo 12211452
yo como usuario del sistema operativo IOS me doy cuenta que me ofrece bastante informacion en cuanto a aplicaciones mas utilizadas, que posicion tienen en el mercado, y no solo eso, si no tambien informacion detallada sobre las mismas con solo un click!, yo la recomiendo....

incluso conoci ciertas aplicaciones que ni en el mundo hacia, no cabe duda que tambien sirve como estrategia para los desarrolladores en ver que aplicacion innovadora falta y ofrecerla.

cabe mencionar que el numero de usuarios de smarthphones se encuentra con Google Play.
yo estare al tanto de App Annie para conocer que pasa con las tiendas de aplicaciones y que puedo descargar en mi ipod

![captura de pantalla de 2015-11-04 13 06 04](https://cloud.githubusercontent.com/assets/13877228/10952623/8cb263f0-82f8-11e5-9d91-aef5d52a5caf.png)

**Comment by alex20078** [comment]
![rene](https://github-cloud.s3.amazonaws.com/assets%2F7757265%2F10957807%2Fb2d86ede-831c-11e5-8fc6-0eaff0ebccfa.png)

Paz Molina Erick Alejandro 12211438

El uso mas recurrente de los "smartphones" y sus aplicaciones ha ocasionado que se creen lugares donde se puedan alojar todas ellas, tiendas como App Store, Google Play, Windows Store se encargan de todo el almacenamiento de las aplicaciones, en la actualidad existen millones de aplicaciones rondando por internet, AppleAnnie se encarga de la estadistica e informacion de cada una de las aplicaciones dentro de cada una de esas tiendas, en opinion personal que tengo un android, la Google Store es una tienda donde se pueden encontrar demasiadas aplicaciones y gratuitas, a diferencia de apple donde muchas veces se tiene que pagar por ellas o las licencias para su programacion en iOS son muy caras.

**Comment by AnaTorresPa** [comment]
App Annie es una herramienta de analisis de las principales tiendas de apps, que son App Store y Google Play, donde permite consultar además algunos de los datos de rendimiento de otras aplicaciones, las de la competencia, como la posición que han ido ocupando desde su lanzamiento en varios países, ademas de darnos esa información de las aplicaciones también nos permite hacer el seguimiento de las redes publicitarias insertadas en nuestras apps y de esta forma integrar todas las herramientas de seguimiento en una sola, sin necesidad de consultar por separado. 

En lo cual se concluye que App Annie se enfoca en analizar mas que nada las aplicaciones que ofrecen App Store y Google Play.Mientras que App Store y Google Play se concentran mas en brindar una gran variedad de aplicaciones a sus usuarios.

Torres Paramo Ana Karen 12211420
![capture1](https://cloud.githubusercontent.com/assets/13877770/10977183/6e26dd38-83a4-11e5-8d02-b4bd728f2d64.PNG)

**Comment by JuanSilvas** [comment]
AppAnnie es una herramienta global que permite la comparación entre los diferentes mercados existentes, esto permitiendo tener una vision más amplia acerca de que es lo que esta siendo mas relativo en el mercado, de tal manera que uno puede enfocarse en analizar cuales juegos o aplicaciones se encuentran con mayor demanda.

Cuenta con unas estadisticas bastante interesantes, dado que se enfoca en la utilización de juegos entre iOs y android, lo cual te permite tener una observación más amplia acerca de las tendencias entre los usuarios, siendo para mi, una gran ventaja ya que mayormente uno se enfoca unicamente en una sola plataforma.

![annieap](https://cloud.githubusercontent.com/assets/4284034/10985900/80c2a5e0-8425-11e5-8168-ba483aac0a63.png)

**Comment by becerrarodriguezraul** [comment]
Becerra Rodriguez Raul 12211902
App Annie proporciona los datos que necesita para informar a todos los aspectos de su estrategia de aplicación móvil. te da acceso a datos más completos sobre descargas de aplicaciones, los ingresos, el total de usuarios activos, la demografía de los usuarios y mucho más.
Compare su composición de la audiencia a sus competidores

Seguimiento de los cambios en la demografía de la base de usuarios de la competencia e identificar las aplicaciones que compiten por la atención de su audiencia.

Identificar un segmento de clientes y la pista de qué aplicaciones de ese grupo utiliza para enfocar sus esfuerzos de adquisición de usuarios.
![image](https://cloud.githubusercontent.com/assets/14007326/10992549/b3b22a66-841b-11e5-9d06-cf44ed50a0f4.png)

**Comment by IoTeacher** [comment]
Gracias por la GiTarea de aqui se evalua la participación.

**Comment by ferminreyes** [comment]
App Annie

Es una pagina con la finalidad de ayudar a los usuarios que desarrollan aplicaciones en un ambito de negocios, esta pagina te ayuda a evaluar el progreso de tu aplicacion tanto como de la competencia, es decir, del progreso de aplicaciones que compitan en el area de enfoque de la aplicacion desarrollada. Una gran utilidad de esta pagina es que las personas desarrolladoras se pueden enfocar en el desarrollo de las aplicaciones, mientras que este servicio te ofrece los reportes y en elaborar las estadisticas del avance ya sea de aceptacion de la aplicacion como su estado en el mercado.
Este tipo de servicios son muy utiles en tanto a nuevas empresas o por emprendedores donde no pueden enfocar sus pocos recursos a cubrir todos los aspectos que demanda el desarrollo de una aplicacion en los mercados de aplicaciones.

**Comment by irvingcastro** [comment]
APP ANNIE
Castro Gaytan Irving Ismael. 11210898 

App annie nos mantiene informados acerca de las actualizaciones de las apps que van saliendo dia a dia asi como tambien las ventas de ellas y las descargas que los usuarios van realizando de dicha app.

Tiene varias secciones como Noticias y revistas de la Play Store.
El principal objetivo es ese , mantenernos al tanto de las apps que van triunfando en la red para asi hacer publicidad de ellas.

![9bs_900](https://cloud.githubusercontent.com/assets/13877823/11079985/e7abfab6-87c4-11e5-8312-5d083ea12048.jpg)
