### ISSUE TITLE
Programa Hola Mundo Objective-C

### ISSUE THREAD

**Issue by EstebanAngeles** [tectijuana/ObjectiveCpdd#58]
No encontraba el issue, no sabia donde poner el print screen de la aplicacion.
@IoTeacher       @abigailmares 
 
![captura de pantalla 2015-10-22 a la s 17 06 26](https://cloud.githubusercontent.com/assets/13890936/10707888/2fed762c-79ad-11e5-8181-eea889ee0645.png)

**Comment by alex20078** [comment]
![captura de pantalla 2015-10-23 a la s 17 56 11](https://cloud.githubusercontent.com/assets/7757265/10708017/eba5809c-79af-11e5-87ef-ca0c764d02db.png)
 Terminado Paz Molina Erick Alejandro 12211438

**Comment by b081191** [comment]
@EstebanAngeles  estaba en un ISSUES que esta cerrado.

**Comment by ilianacm** [comment]
@IoTeacher  Ya había hablado con usted maestro, le dejo el screenshot, gracias 

![12193016_922248367842607_1639551084_o](https://cloud.githubusercontent.com/assets/14007302/10780414/628a53f2-7cfa-11e5-9b23-18e19d7d819e.jpg)

**Comment by Alberto80** [comment]
Hola Mundo Terminado!
#12211964 - @IoTeacher 

![holamundo](https://cloud.githubusercontent.com/assets/14007333/10780461/d789f1ee-7cfa-11e5-83c5-e62089bf3393.jpg)

**Comment by IoTeacher** [comment]
# @ilianacm  y @Alberto80 favor de elaborar los otros 10 programas, este bloque de HelloWorld se vencio el viernes pasado ahora son 11 checar Milestone por favor. Gracias por atender este mensaje

**Comment by IoTeacher** [comment]
# @EstebanAngeles @b081191 @alex20078 son 100 en el programa HelloWorld. Resto atender milestone 11 Apps
