### ISSUE TITLE
Opinion de los Articulos

### ISSUE THREAD

**Issue by odairrobles** [tectijuana/ObjectiveCpdd#59]
Apple’s Swift Is Killing Objective-C

en este articulo se da a conocer el nuevo lenguaje (Swift) que al parecer tendrá mayores ventajas sobre el Objetive c que ya conocemos, por que es mas fácil de aprender y de usar.
si no conoces nada de lenguajes de programación, este nuevo lenguaje sera útil para empezar a programar, y con el podremos desarrollar aplicaciones muy interesantes. 

9 developer trends you can bank on in 2016

en el mundo de la computación-sistemas, etc. el individuo debe estar actualizándose constantemente por que cada día que pasa salen nuevas tecnologías, nuevas tendencias, es por eso que deben buscar información reciente a cada instante y no quedarse con información o programas o técnicas con las cuales se sientan cómodos, si no con las que serán necesarias  y utiles para desarrollar nuestros objetivos.

Insider: Oracle has lost interest in Java

al parecer java esta siendo poco a poco menos utilizado, lo están mandando al olvido por lo mismo que día a día van saliendo nuevas formas y técnicas para programar, pero así es esto, cada vez surgen nuevos programas nuevos lenguajes y como son mas fáciles e intuitivos para programar, se van olvidando los viejos programas, los viejos lenguajes.
java es una buena forma de programar, y aun se siguen usando y se usara por un largo tiempo.

Odair Robles Paz # 12210436

**Comment by IoTeacher** [comment]
@odairrobles Gracias por la participación.
